import pandas as pd
import os

# Snakefile Last edit: 03/28/2018 

# Usage
## Dry run to check if snakefile works
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 50 -np
## Actual run
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 10

design_info = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_info_design.csv")
firth = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_firth.tsv")
firth_norm = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_firth_norm.tsv")

rule all:
  input:
    design_info,
    firth,
    firth_norm

# Outputs ordered sample info with subject type and age
rule design_info:
  input:"as_symp_HD_design.py"
  output:
    info = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_info_design.csv"),
    filt = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_filter.csv"),
    nor = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_from_norm.csv")
  shell:
    "python {input}"

# Normalize counts
rule norm:
  input:os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_filter.csv")
  output:os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_norm.csv")
  shell:
    """detk-norm deseq2 {input} -o {output}"""

# DE Firth
rule firth:
  input:
    counts = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_norm.csv"),
    info= os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_info_design.csv")
  params:
    design="Subject_type[HD] ~ Subject_death + counts"
  output:os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_firth.tsv")
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

# DE Firth from sample normalized counts
rule firth_norm:
  input:
    counts = os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_from_norm.csv"), 
    info= os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_info_design.csv")
  params:
    design="Subject_type[HD] ~ Subject_death + counts"
  output:os.path.abspath("../../../samples/Analysis_Results/as_symp_HD_firth_norm.tsv")
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""






