# Snakefile
# Usage
import pandas as pd

## Dry run to check if snakefile works
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 50 -np
## Actual run
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 10

design_info = "asymp_info_design.csv"
firth = "asymp_salmon_firth.csv"

rule all:
  input:
    design_info,
    firth

# Outputs ordered sample info with subject type and age
# Outputs filtered CAP samples
rule design_info:
  input:"asymp_design.py"
  output:
    info="asymp_info_design.csv",
    norm="asymp_salmon_filter.csv"
  shell:
    "python {input}"

# Normalize filtered samples
rule norm:
  input:"asymp_salmon_filter.csv"
  output:"asymp_salmon_norm.csv"
  shell:
    """detk-norm deseq2 {input} -o {output}"""

# firth
rule firth:
  input:
    counts = "asymp_salmon_norm.csv",
    info= "asymp_info_design.csv"
  params:
    design="Subject_type[CAP] ~ Subject_death + counts"
  output:"asymp_salmon_firth.csv"
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

