import pandas as pd, os, glob

# Usage: snakemake --nolock --cluster "qsub -P mlhd -cwd -l h_rt=72:00:00" --jobs 50 --snakefile snake_samples_py

n1 = [100]
n2 = [92]
bm = list(range(1,7,1))
#bm = list(range(1,3,1))
#df_counts = expand(os.path.abspath("../../../samples/Analysis_Results/CAU_synth_matrix/df_combi{n1}_{n2}.csv"), n1 = n1, n2 = n2)
#pairs_df = expand(os.path.abspath("../../../samples/Analysis_Results/CAU_synth_matrix/df_combi{n1}_{n2}_bm{basemean}.csv"), n1=n1, n2=n2, basemean = bm)
combi_pairs= expand(os.path.abspath("../../../samples/Analysis_Results/CAU_synth_matrix/df_combi{n1}_{n2}_bm{basemean}.csv"), n1=n1, n2=n2, basemean = bm)

rule all:
    input:
        combi_pairs,
#        df_counts,
#        pairs_df

#rule df_counts:
#    input: 
#        py = 'sample_gtex_counts.py',
#        counts = os.path.abspath("../../../samples/Analysis_Results/GTEx_salmon_quant.tsv")
#    params:
#        n1 = '{n1}',
#        n2 = '{n2}'
#    output: os.path.abspath('../../../samples/Analysis_Results/CAU_synth_matrix/df_combi{n1}_{n2}.csv')
#    shell:
#        "python {input.py} {input.counts} {params.n1} {params.n2}"

rule pairs_df:
    input: 
        py = 'synth_mat_bm_combi.py',
        counts = os.path.abspath("../../../samples/Analysis_Results/CAU_synth_matrix/df_combi{n1}_{n2}.csv")
    params: bme = '{basemean}'
    output: os.path.abspath("../../../samples/Analysis_Results/CAU_synth_matrix/df{n1}_{n2}_pairs_baseExp{basemean}.csv")
    shell:
        "python {input.py} {input.counts} {params.bm}"

rule combi_pairs:
    input:
        py = 'sample_gtex_counts_combi.py',
        counts = os.path.abspath("../../../samples/Analysis_Results/GTEx_salmon_quant.tsv")
    params:
        n1 = '{n1}',
        n2 = '{n2}',
        bm = '{basemean}'
    output: os.path.abspath("../../../samples/Analysis_Results/CAU_synth_matrix/df_combi{n1}_{n2}_bm{basemean}.csv")
    shell:
        "python {input.py} {input.counts} {params.n1} {params.n2} {params.bm}"
