import pandas as pd
import os

# Snakefile

# Usage
## Dry run to check if snakefile works
# snakemake --nolock -np --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 50
## Actual run
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 10

design_info = os.path.abspath("../../samples/Analysis_Results/all_info_design.csv")
firth = os.path.abspath("../../samples/Analysis_Results/all_firth.tsv")

rule all:
  input:
    design_info,
    firth

# Outputs ordered sample info with subject type and age
rule design_info:
  input:"design_all.py"
  output:
    info = os.path.abspath("../../samples/Analysis_Results/all_info_design.csv"),
    filt = os.path.abspath("../../samples/Analysis_Results/all_filter.csv")
  shell:
    "python {input}"

# Normalize counts
rule norm:
  input:os.path.abspath("../../samples/Analysis_Results/all_filter.csv")
  output:os.path.abspath("../../samples/Analysis_Results/all_norm.csv")
  shell:
    """detk-norm deseq2 {input} -o {output}"""

# DE Firth
rule firth:
  input:
    counts = os.path.abspath("../../samples/Analysis_Results/all_norm.csv"),
    info= os.path.abspath("../../samples/Analysis_Results/all_info_design.csv")
  params:
    design="Subject_type[Control] ~ Subject_death + counts"
  output:os.path.abspath("../../samples/Analysis_Results/all_firth.tsv")
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

# Returns significant counts and genes 
rule sig:
  input:
    py = "significant_firth.py",
    firth = os.path.abspath("../../samples/all_salmon_firth.csv"),
    mart = "mart_export.txt"
  output:os.path.abspath("../../samples/all_salmon_firth_sig_counts.csv")
  shell:
    """./{input.py} {input.firth} {input.mart}"""
