import pandas as pd
import os

# Snakefile last edit: 05/3/2018
# Usage
## Dry run to check if snakefile works 
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 50 -np
## Actual run
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 10

design_info = os.path.abspath("../../samples/Analysis_Results/BA9_info_design.csv")
firth = os.path.abspath("../../samples/Analysis_Results/BA9_firth.tsv")
firth_norm = os.path.abspath("../../samples/Analysis_Results/BA9_firth_norm.tsv")

rule all:
  input:
    design_info,
    firth,
    firth_norm

# Outputs ordered sample info with subject type and age
# Outputs filtered CAP samples
rule design_info:
  input:"BA9_design.py"
  output:
    info=os.path.abspath("../../samples/Analysis_Results/BA9_info_design.csv"),
    norm=os.path.abspath("../../samples/Analysis_Results/BA9_filter.csv"),
    nor=os.path.abspath("../../samples/Analysis_Results/BA9_from_norm.csv")
  shell:
    "python {input}"

# Normalize filtered samples
rule norm:
  input:os.path.abspath("../../samples/Analysis_Results/BA9_filter.csv")
  output:os.path.abspath("../../samples/Analysis_Results/BA9_norm.csv")
  shell:
    """detk-norm deseq2 {input} -o {output}"""

# firth
rule firth:
  input:
    counts = os.path.abspath("../../samples/Analysis_Results/BA9_norm.csv"),
    info= os.path.abspath("../../samples/Analysis_Results/BA9_info_design.csv")
  params:
    design="Subject_type[Control] ~ Subject_death + counts"
  output:os.path.abspath("../../samples/Analysis_Results/BA9_firth.tsv")
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

rule firth_norm:
  input:
    counts = os.path.abspath("../../samples/Analysis_Results/BA9_from_norm.csv"),
    info= os.path.abspath("../../samples/Analysis_Results/BA9_info_design.csv")
  params:
    design="Subject_type[Control] ~ Subject_death + counts"
  output:os.path.abspath("../../samples/Analysis_Results/BA9_firth_norm.tsv")
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

