#!/bin/bash
#$ -P mlhd
#$ -cwd

export LC_ALL=en_US.utf-8
export LANG=$LC_ALL

dir=/usr3/graduate/crespodi/Huntington/presymptomatic_hd_mrnaseq/samples/

samplesdir=/usr3/graduate/crespodi/Huntington/presymptomatic_hd_mrnaseq/samples/H_0014_BA9_mRNASeq*
prefix=/usr3/graduate/crespodi/Huntington/presymptomatic_hd_mrnaseq/samples/H_0014_BA9_mRNASeq.multiqc_report

multiqc -n $prefix -outdir $dir $samplesdir
