#!/bin/bash
#$ -P mlhd
#$ -cwd

export LC_ALL=en_US.utf-8
export LANG=$LC_ALL

# Output directory
dir=/usr3/graduate/fiagus/presymptomatic_hd_mrnaseq/samples/

# Samples
samp=/usr3/graduate/fiagus/presymptomatic_hd_mrnaseq/samples

# Ignore
#ign=/usr3/graduate/fiagus/presymptomatic_hd_mrnaseq/samples/H_*_BA9_mRNASeq_100k.*.fastq.gz

# Ouput name
out=/usr3/graduate/fiagus/presymptomatic_hd_mrnaseq/samples/ALL_mRNASeq.multiqc_report

multiqc -n $out -o $dir $samp
