
rule fastqc:
    input:
        "/usr3/graduate/crespodi/Huntington/presymptomatic_hd_mrnaseq/samples/{sample}.fastq.gz"
    output:
        "/usr3/graduate/crespodi/Huntington/presymptomatic_hd_mrnaseq/samples/{sample}.fastqc.zip"
        "/usr3/graduate/crespodi/Huntington/presymptomatic_hd_mrnaseq/samples/{sample}.fastqc.html"
    shell:
        "fastqc {input} - > {output}"

