# Snakefile
# Usage
## Dry run to check if snakefile works
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 50 -np
## Actual run
# snakemake --nolock --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 10

design_info = "CAP_info_design.csv"
firth = "CAP_salmon_firth.csv"

rule all:
  input:
    design_info,
    firth

# Outputs ordered sample info with subject type and age
# Outputs filtered CAP samples
rule design_info:
  input:"design.py"
  output:
    info="CAP_info_design.csv",
    norm="CAP_salmon_filter.csv"
  shell:
    "python {input}"

# Normalize filtered samples
rule norm:
  input:"CAP_salmon_filter.csv"
  output:"CAP_salmon_norm.csv"
  shell:
    """detk-norm deseq2 {input} -o {output}"""

# firth
rule firth:
  input:
    counts = "CAP_salmon_norm.csv",
    info= "CAP_info_design.csv"
  params:
    design="Subject.subject_type ~ Subject.death"
  output:"CAP_salmon_firth.csv"
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""
