# snakemake --nolock -np --cluster "qsub -P mlhd -cwd -pe omp {threads}" --jobs 50
#REFERENCE
gtex_pheno = os.path.abspath(
    "../reference/phs000424.v7.pht002742.v7.p2.c1.GTEx_Subject_Phenotypes.GRU.txt")
GTEX_deseq_r = os.path.abspath("../../analysis/GTEx_diff_exp/GTEX_deseq2_filter.R")
GTEX_info = "GTEx_info.tsv"

workdir: "../../samples/GTEx/"

# Output files
filter_rows = "GTEx_salmon_filter.csv"

#Firth
GTEX_norm = "GTEx_salmon_norm.csv"
GTEX_design_info = "GTEx_design_sex_age.tsv"

#DESEq2
GTEX_deseq_design = "GTEx_deseq_design.csv"
GTEX_deseq_out = "GTEx_filter_deseq2_results.csv"


GTEX_firth = "GTEx_salmon_firth_sex_age.tsv"
#GTEX_firth = "GTEx_firth_without_HD.tsv"



rule all:
  input:
    filter_rows,
    GTEX_norm,
    GTEX_design_info,
    GTEX_firth,
    GTEX_deseq_design,
    GTEX_deseq_out,



#================================Pre-Processing===========================================#
# filter rows with means less than 5
rule create_filtered_rows:
  input:
      quant = "GTEx_salmon_quant.tsv"
  output:
      filter_fn = filter_rows
  run:
      import pandas as pd
      fn = input.quant
      ALL_GTEX = pd.read_csv(fn, sep="\t", index_col=['gene_id'])
      # get ba9 and cau samples and put them in a list
      ba9 = ALL_GTEX.filter(regex="^GTEX-.*BA9.*").columns.tolist()
      cau = ALL_GTEX.filter(regex="^GTEX-.*CAU.*").columns.tolist()
      # Drop the Unnamed column which is just an index
      if "Unnamed: 0" in ALL_GTEX.columns:
          ALL_GTEX = ALL_GTEX.drop("Unnamed: 0", axis=1)
      else:
          # Take the meas of ba9 and cau samples and create new columns
          ALL_GTEX["avg_ba9"] = ALL_GTEX[ba9].mean(axis=1)
          ALL_GTEX["avg_cau"] = ALL_GTEX[cau].mean(axis=1)
          
          ALL_GTEX = ALL_GTEX[(ALL_GTEX.avg_ba9 > 5) | (ALL_GTEX.avg_cau > 5)]          
          ALL_GTEX = ALL_GTEX.drop("avg_ba9", axis=1)
          ALL_GTEX = ALL_GTEX.drop("avg_cau", axis=1)
          
          GTEX_DF = ALL_GTEX.filter(regex="GTEX-.*")

          GTEX_DF.to_csv(output.filter_fn, index=True)
    

#================================Firth Logistic Regression===========================================
# Outputs ordered sample info with subject type and age
rule create_design_file_firth:
    input:
        info = GTEX_info,
        pheno_info = gtex_pheno
    output:
        sample_info = GTEX_design_info
    run:
        import pandas as pd
        gtex = pd.read_csv(input.info, sep="\t")
        cols = ["SUBJID", "SEX", "AGE"]

        # Info file that comes with GTEX data
        attrib = pd.read_csv(input.pheno_info,
                             sep="\t",comment="#", usecols=cols)

        attrib["sample_name"] = [_.split("-")[1] for _ in attrib["SUBJID"].tolist()]

        # add sex and age to info file
        merged_df = gtex.merge(attrib, left_on="sample_name", right_on="sample_name", how="outer")
        merged_df = merged_df[["identifier", "brain_region","SEX", "AGE"]]
        merged_df = merged_df.dropna(axis=0)
        merged_df = merged_df.set_index(["identifier"])

        # Keep one pair of sample data
        merged_df = merged_df.filter(like="_R1", axis=0)
        merged_df["identifier"] = [_.rsplit("_", 1)[0] for _ in merged_df.index.tolist()]
        final_df = merged_df[["identifier", "brain_region","SEX", "AGE"]]
        final_df.to_csv("GTEx_design_sex_age.tsv", sep="\t", index=False)


          
# Normalize the filtered matrix
rule create_norm:
  input:
      filter_rows
  output:
      GTEX_norm
  shell:
    """detk-norm deseq2 {input} -o {output}"""

# Performs firth logistic regression on normalized GTEX data
rule create_firth:
  input:
    counts = GTEX_norm,
    info = GTEX_design_info
  params:
    design ="brain_region[CAU] ~ SEX+AGE+counts"
  output:
      GTEX_firth
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

#=======================================DESeq2======================================================
rule create_deseq_design:
    input:
        gtex = "GTEx_info.tsv"
    output:
        design = GTEX_deseq_design
    run:
        import os, pandas as pd        
        info_file = pd.read_csv(input.gtex, sep='\t', usecols=['identifier', 'brain_region'])

        # We just need the sample names
        subset_info = info_file[info_file['identifier'].str.endswith('_R1')]
        subset_info['identifier'] = [_.rsplit('_', 1)[0] for _ in subset_info['identifier'].tolist()]
        subset_info.to_csv(output.design, sep=',', index=False)

# Run DESeq2 on the gtex samples
rule create_GTEX_filter_deseq:
  input:
      gtex = GTEX_deseq_r,
      filtered = filter_rows
      
  output: GTEX_deseq_out
  shell:
      "Rscript {input.gtex}"
