
#include: '../common_workflow.snake'

design = "sample_info_design.csv"
head = "head_all_salmon_quant_norm.csv"
firth_head = "head_all_samples_firth.csv"

rule all:
  input:
    design,
    head,
    firth_head

# Outputs ordered sample info with subject type and age
rule get_design_R:
  input: 
    R="pull_sample.R",
    counts= "../../samples/all_salmon_quant.tsv"
  output:"sample_info_design.csv"
  shell:
    "Rscript {input.R} {input.counts}"

# Test makes a file with first 100 lines
rule head:
  input:"../../samples/all_salmon_quant_norm.csv"
  output:"head_all_salmon_quant_norm.csv"
  shell:
    "head -n 101 {input} > {output}"

# Test for firth
rule head_counts:
  input:
    counts="head_all_salmon_quant_norm.csv",
    info="sample_info_design.csv"
  params: 
    design="Subject.subject_type ~ Subject.death"
  output: "head_all_samples_firth.csv"
  shell:
    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""

# Firth
#rule firth:
#  input: 
#    counts= "../../samples/all_salmon_quant_norm.csv",
#    info= "sample_info_design.csv"
#  params: 
#    design="Subject.subject_type ~ Subject.death"
#  output: "all_samples_firth.csv"
#  shell:
#    """detk-de firth "{params.design}" {input.counts} {input.info} -o {output}"""
